version: '3'

services:
  frontend:
      build:
        context: frontend
      tty: true
      volumes:
        - ./frontend/app:/frontend/app
      ports:
        - 3000:3000
      environment:
        - WATCHPACK_POLLING=true
        
  backend:
    build:
      context: backend
    tty: true
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
      container_name: pgadmin4
      image: dpage/pgadmin4
      ports:
        - 8888:80
      volumes:
        - pgadmin4_data:/var/lib/pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: root@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
      hostname: pgadmin4
      depends_on:
        - db

volumes:
  postgres_data:
    name: postgres_data
  pgadmin4_data:
    name: pgadmin4_data
